export const FETCH_BOOKS_START = "FETCH_BOOKS_START";
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS'
export const FETCH_BOOKS_FAIL = "FETCH_BOOKS_FAIL";

export const SEARCH_DATA = 'SEARCH_DATA';